config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :playlists
  resources :welcome, only: :index

  root 'welcome#index'

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base

	belongs_to :user
	has_many :songs

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :playlists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

	before_action :authenticate_user!

	def index
		@playlists = Playlist.where(user_id: current_user.id)
	end

	def create
		  @playlist = Playlist.new(playlist_params)
		  @playlist.user_id = current_user.id 
		if @playlist.save
			respond_to do |format|
				format.html { redirect_to playlist_path}
				format.json	{render :json => @playlist}
			end
		end
	end

	def new
		@playlist = Playlist.new
	end

	def edit
	end

	def show
		
	end

	def update
	end

	def destroy
	end

private

def playlist_params
	params.require(:playlist).permit(:track, :artist)
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		# if user_signed_in? 
		# 	redirect_to '/playlists'
		# end
	end

end

app/controllers/welcomes_controller.rb
class WelcomeController < ApplicationController

	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Next</title>
  <link href='http://fonts.googleapis.com/css?family=Muli:300,400' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>

  <div class="wrapper">
    <header>
    	<p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <h1>&#9738;</h1>
  	<div class="signin">
    	<% if user_signed_in? %>
  		<%= link_to "New Playlist", playlists_path %> | Signed in as <%= current_user.email %> | Not you? <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Sign In', new_user_session_path %>
  	  <% end %>
  	</div> 
    </header>

    <div class="container">

      <%= yield %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    </div>
  </div>

  <div class="push"></div>

  <footer> Copyright 2014 </footer>
  
</body>
</html>

app/views/playlists/index.html.erb
	<div class="logo">&#127911;</div>

		<div class="pl-saved">
			<h2 class="pl-h2">Search for a Track</h2>
				<form id="search">
				  <label for="track">Track</label>
				  <input type="search" id="track">
				  <br>
				  <label for="artist">Artist</label>
				  <input type="search" id="artist">
				  <br>
				  <input type="submit" value="Search">
				</form>

		</div>

		

app/views/playlists/new.html.erb
<div class="new-search-bar">
	<button id="new-search"> search </button>
</div> 

<div class="new-container-left">
	<div class="new-song-info">
		<h3> Now Playing: </h3>
		<h5> Artist: </h5>
		<!-- Album Cover Image ADD RUBY --> 
		<img src=""/>
	</div>
	<div class="new-played-songs">
		<button id="new-played">Played</button>
		<button id="new-save">Save</button>
		<section>
			<li>Artist:</li> <!-- Artist Name -->
			<li>Song:</li> <!-- Song Name -->
		</section>
	</div> 
</div>

<div class="new-container-right">
	<div class="new-upcoming">
		<h3>Upcoming Songs</h3>
	</div>
</div>

app/views/welcome/index.html.erb
 <div class="landing-bg">

 <div class="landing-float-top-lt">
 	<span class="landing-large-text">Find Your <em>NEXT</em> Jam</span>
 </div>

 <div class="clearfix"></div>

	<div class="landing-body">
		<p class="landing-body-text">
			Intuitive playlists for music exploration.
		</p>
		<a href="/playlists"><button class="landing-button" name="button">Get Started</button></a>

	</div>

 <div class="clearfix"></div>

</div>